[package]
name = "bevy_lint"
version = "0.1.0"
authors = ["MinerSebas <scherthan_sebastian@web.de>"]
description = "Provides Lints for Bevy Code"
edition = "2018"
publish = false
license = "MIT OR Apache-2.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
clippy_utils = { git = "https://github.com/rust-lang/rust-clippy", tag = "rust-1.56.0" }
dylint_linting = "1.0.7"
if_chain = "1.0.2"
either = "1.6.1"
itertools = "0.10.1"


[dev-dependencies]
dylint_testing = "1.0.7"
bevy = { git = "https://github.com/bevyengine/bevy.git", rev = "6a8a8c9d21f32e0e46623db9438813b009f9e014", default-features = false }

[package.metadata.rust-analyzer]
rustc_private = true

[[example]]
name = "bundle_with_incomplete_transforms"
path = "ui/bundle_with_incomplete_transforms.rs"

[[example]]
name = "empty_query"
path = "ui/empty_query.rs"

[[example]]
name = "filter_in_world_query"
path = "ui/filter_in_world_query.rs"

[[example]]
name = "insert_resource_with_default"
path = "ui/insert_resource_with_default.rs"

[[example]]
name = "unnecessary_change_detection_filters"
path = "ui/unnecessary_change_detection_filters.rs"

[[example]]
name = "unnecessary_option"
path = "ui/unnecessary_option.rs"

[[example]]
name = "unnecessary_or"
path = "ui/unnecessary_or.rs"

[[example]]
name = "unnecessary_with"
path = "ui/unnecessary_with.rs"
