name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Format
        run: cargo +stable fmt && git diff --exit-code

      - name: Install cargo-dylint
        run: cargo install cargo-dylint

      - name: Install dylint-link
        run: cargo install dylint-link

      - name: Build
        run: cargo build

      - name: List
        run: DYLINT_LIBRARY_PATH=$PWD/target/debug cargo dylint --list | grep -w fill_me_in

      - name: Test
        run: cargo test
