name: CI

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        id: cache
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            ~/.dylint_drivers
            target/
            crates/bevy_lint/target
          key: ${{ runner.os }}-cargo-dylint-${{ hashFiles('**/Cargo.toml') }}

      - name: Install alsa and udev
        run: sudo apt-get update; sudo apt-get install --no-install-recommends libasound2-dev libudev-dev

      - name: Install dylint
        run: cargo install cargo-dylint; cargo install dylint-link
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Check Format
        run: cargo fmt --all -- --check

      - name: Check Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings -A clippy::type_complexity

      - name: Run Tests
        run: cargo test
        env:
          # Can be removed once https://github.com/trailofbits/dylint/pull/48 is merged and released
          CARGO_TERM_COLOR: never

      - name: Run Doc Tests
        run: sed -i 's/cdylib/lib/g' Cargo.toml; cargo test --doc
